---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  namespace: webapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: devops-webapp
  template:
    metadata:
      labels:
        app: devops-webapp
    spec:
      containers:
      - image: <IMAGE_TAG>
        name: webapp
        env:
        - name: CONTAINER_NETWORK
          value: "none"
        - name: CONTAINER_SOCAT_ENABLED
          value: "false"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
spec:
  type: LoadBalancer
  selector:
    app: devops-webapp
  ports:
  - port: 80
    targetPort: 8080


