---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  namespace: webapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: devops-webapp
  template:
    metadata:
      labels:
        app: devops-webapp
    spec:
      containers:
      - image: ...
        name: webapp
        ...
---
apiVersion: v1
kind: Service
metadata:
...
spec:
...


